# Generated by Django 2.1.2 on 2018-11-02 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_colaborator_employee_people'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaborator',
            name='codigo_profissional',
            field=models.CharField(blank=True, help_text='Código do profissional', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='colaborator',
            name='interno',
            field=models.BooleanField(default=False, help_text='O profissional é interno ou não.'),
        ),
        migrations.AddField(
            model_name='employee',
            name='ctps',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='salario',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
    ]
