# Generated by Django 2.1.2 on 2018-10-08 23:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ctp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('modificado_em', models.DateTimeField(auto_now=True, verbose_name='modificado em')),
                ('ativo', models.BooleanField(default=True)),
                ('titulo', models.CharField(max_length=100)),
                ('altura', models.PositiveIntegerField(blank=True, null=True)),
                ('largura', models.PositiveIntegerField(blank=True, null=True)),
                ('quantidade', models.PositiveIntegerField(blank=True, null=True)),
                ('recomendacao', models.TextField(blank=True, null=True)),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='')),
                ('status', models.CharField(choices=[('abe', 'Aberto'), ('rec', 'Recebido'), ('pro', 'Produção'), ('fin', 'Finalizado'), ('sai', 'Saída'), ('ent', 'Entregue')], default='abe', max_length=3)),
                ('opcao', models.TextField(blank=True, null=True, verbose_name='opção')),
                ('reticula', models.CharField(choices=[('con', 'convencional'), ('sub', 'sublimática'), ('est', 'estocástica')], default='con', max_length=3, verbose_name='retícula')),
                ('chapa', models.BooleanField(default=False, verbose_name='chapas forneadas')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
            ],
            options={
                'verbose_name': 'CTP',
                'verbose_name_plural': 'CTPs',
            },
        ),
        migrations.CreateModel(
            name='FineArt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('modificado_em', models.DateTimeField(auto_now=True, verbose_name='modificado em')),
                ('ativo', models.BooleanField(default=True)),
                ('titulo', models.CharField(max_length=100)),
                ('altura', models.PositiveIntegerField(blank=True, null=True)),
                ('largura', models.PositiveIntegerField(blank=True, null=True)),
                ('quantidade', models.PositiveIntegerField(blank=True, null=True)),
                ('recomendacao', models.TextField(blank=True, null=True)),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='')),
                ('status', models.CharField(choices=[('abe', 'Aberto'), ('rec', 'Recebido'), ('pro', 'Produção'), ('fin', 'Finalizado'), ('sai', 'Saída'), ('ent', 'Entregue')], default='abe', max_length=3)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
            ],
            options={
                'verbose_name': 'FineArt',
                'verbose_name_plural': 'FineArts',
            },
        ),
        migrations.CreateModel(
            name='Formato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'formato',
                'verbose_name_plural': 'formatos',
                'ordering': ('titulo',),
            },
        ),
        migrations.CreateModel(
            name='Fotolito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('modificado_em', models.DateTimeField(auto_now=True, verbose_name='modificado em')),
                ('ativo', models.BooleanField(default=True)),
                ('titulo', models.CharField(max_length=100)),
                ('altura', models.PositiveIntegerField(blank=True, null=True)),
                ('largura', models.PositiveIntegerField(blank=True, null=True)),
                ('quantidade', models.PositiveIntegerField(blank=True, null=True)),
                ('recomendacao', models.TextField(blank=True, null=True)),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='')),
                ('status', models.CharField(choices=[('abe', 'Aberto'), ('rec', 'Recebido'), ('pro', 'Produção'), ('fin', 'Finalizado'), ('sai', 'Saída'), ('ent', 'Entregue')], default='abe', max_length=3)),
                ('cores', models.CharField(blank=True, max_length=10, null=True, verbose_name='número de cores')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
                ('formato', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bureau.Formato')),
            ],
            options={
                'verbose_name': 'fotolito',
                'verbose_name_plural': 'fotolitos',
            },
        ),
        migrations.CreateModel(
            name='Lineatura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=5)),
            ],
            options={
                'verbose_name': 'lineatura',
                'verbose_name_plural': 'lineaturas',
                'ordering': ('titulo',),
            },
        ),
        migrations.CreateModel(
            name='Papel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'papel',
                'verbose_name_plural': 'papéis',
                'ordering': ('titulo',),
            },
        ),
        migrations.CreateModel(
            name='ProvaDeCor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('modificado_em', models.DateTimeField(auto_now=True, verbose_name='modificado em')),
                ('ativo', models.BooleanField(default=True)),
                ('titulo', models.CharField(max_length=100)),
                ('altura', models.PositiveIntegerField(blank=True, null=True)),
                ('largura', models.PositiveIntegerField(blank=True, null=True)),
                ('quantidade', models.PositiveIntegerField(blank=True, null=True)),
                ('recomendacao', models.TextField(blank=True, null=True)),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='')),
                ('status', models.CharField(choices=[('abe', 'Aberto'), ('rec', 'Recebido'), ('pro', 'Produção'), ('fin', 'Finalizado'), ('sai', 'Saída'), ('ent', 'Entregue')], default='abe', max_length=3)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
                ('formato', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bureau.Formato')),
                ('papel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bureau.Papel', verbose_name='papéis')),
            ],
            options={
                'verbose_name': 'Prova de Cor',
                'verbose_name_plural': 'Provas de Cor',
            },
        ),
        migrations.AddField(
            model_name='fotolito',
            name='lineatura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bureau.Lineatura'),
        ),
        migrations.AddField(
            model_name='fineart',
            name='formato',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bureau.Formato'),
        ),
        migrations.AddField(
            model_name='fineart',
            name='papel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bureau.Papel', verbose_name='papéis'),
        ),
        migrations.AddField(
            model_name='ctp',
            name='formato',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bureau.Formato'),
        ),
        migrations.AddField(
            model_name='ctp',
            name='lineatura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bureau.Lineatura'),
        ),
    ]
