# Generated by Django 2.1.2 on 2018-10-06 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fotolito',
            options={'verbose_name': 'fotolito', 'verbose_name_plural': 'fotolitos'},
        ),
    ]
