# Generated by Django 2.1.2 on 2018-10-06 18:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0004_auto_20181006_1458'),
    ]

    operations = [
        migrations.CreateModel(
            name='Papel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('papel', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ProvaDeCor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('modificado_em', models.DateTimeField(auto_now=True, verbose_name='modificado em')),
                ('titulo', models.CharField(max_length=100)),
                ('altura', models.PositiveIntegerField(blank=True, null=True)),
                ('largura', models.PositiveIntegerField(blank=True, null=True)),
                ('quantidade', models.PositiveIntegerField(blank=True, null=True)),
                ('recomendacao', models.TextField(blank=True, null=True)),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='')),
                ('ativo', models.BooleanField(default=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
                ('formato', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Formato')),
                ('papel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Papel', verbose_name='papéis')),
            ],
            options={
                'verbose_name': 'ProvaDeCor',
                'verbose_name_plural': 'ProvaDeCors',
            },
        ),
        migrations.AlterModelOptions(
            name='ctp',
            options={'verbose_name': 'CTP', 'verbose_name_plural': 'CTPs'},
        ),
        migrations.AddField(
            model_name='ctp',
            name='papel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Papel', verbose_name='papéis'),
        ),
        migrations.AddField(
            model_name='fotolito',
            name='papel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Papel', verbose_name='papéis'),
        ),
    ]
