# Generated by Django 2.1.2 on 2018-10-06 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20181006_1528'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formato',
            options={'ordering': ('titulo',), 'verbose_name': 'formato', 'verbose_name_plural': 'formatos'},
        ),
        migrations.AlterModelOptions(
            name='lineatura',
            options={'ordering': ('titulo',), 'verbose_name': 'lineatura', 'verbose_name_plural': 'lineaturas'},
        ),
        migrations.AlterModelOptions(
            name='papel',
            options={'ordering': ('titulo',), 'verbose_name': 'papel', 'verbose_name_plural': 'papéis'},
        ),
        migrations.AlterModelOptions(
            name='provadecor',
            options={'verbose_name': 'Prova de Cor', 'verbose_name_plural': 'Provas de Cor'},
        ),
    ]
