# Generated by Django 2.1.2 on 2018-10-06 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_fineart'),
    ]

    operations = [
        migrations.AddField(
            model_name='ctp',
            name='status',
            field=models.CharField(choices=[('abe', 'Aberto'), ('rec', 'Recebido'), ('pro', 'Produção'), ('fin', 'Finalizado'), ('sai', 'Saída'), ('ent', 'Entregue')], default='abe', max_length=3),
        ),
        migrations.AddField(
            model_name='fineart',
            name='status',
            field=models.CharField(choices=[('abe', 'Aberto'), ('rec', 'Recebido'), ('pro', 'Produção'), ('fin', 'Finalizado'), ('sai', 'Saída'), ('ent', 'Entregue')], default='abe', max_length=3),
        ),
        migrations.AddField(
            model_name='fotolito',
            name='status',
            field=models.CharField(choices=[('abe', 'Aberto'), ('rec', 'Recebido'), ('pro', 'Produção'), ('fin', 'Finalizado'), ('sai', 'Saída'), ('ent', 'Entregue')], default='abe', max_length=3),
        ),
        migrations.AddField(
            model_name='provadecor',
            name='status',
            field=models.CharField(choices=[('abe', 'Aberto'), ('rec', 'Recebido'), ('pro', 'Produção'), ('fin', 'Finalizado'), ('sai', 'Saída'), ('ent', 'Entregue')], default='abe', max_length=3),
        ),
        migrations.AlterField(
            model_name='ctp',
            name='reticula',
            field=models.CharField(choices=[('con', 'convencional'), ('sub', 'sublimática'), ('est', 'estocástica')], default='con', max_length=3, verbose_name='retícula'),
        ),
    ]
