# Generated by Django 2.1.2 on 2018-10-08 18:47

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('core', '0010_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonPF',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('ativo', models.BooleanField(default=True)),
                ('person_type', models.CharField(blank=True, choices=[('PF', 'Pessoa Física'), ('PJ', 'Pessoa Jurídica')], max_length=2, null=True)),
                ('rg', models.CharField(blank=True, max_length=255, null=True)),
                ('cpf', models.CharField(blank=True, max_length=255, null=True)),
                ('birthdate', models.DateField(blank=True, null=True, verbose_name='Data de Nascimento')),
            ],
            options={
                'verbose_name': 'Cadastro Pessoa Física',
                'verbose_name_plural': 'Cadastro de Pessoas Físicas',
            },
            bases=('auth.user', models.Model),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='PersonPJ',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('ativo', models.BooleanField(default=True)),
                ('person_type', models.CharField(blank=True, choices=[('PF', 'Pessoa Física'), ('PJ', 'Pessoa Jurídica')], max_length=2, null=True)),
                ('company_name', models.CharField(max_length=255, verbose_name='Razão Social')),
                ('cnpj', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Cadastro Pessoa Jurídica',
                'verbose_name_plural': 'Cadastro de Pessoas Jurídicas',
            },
            bases=('auth.user', models.Model),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
