# Generated by Django 2.1.2 on 2018-10-08 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_personpf_personpj'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personpf',
            options={'ordering': ('first_name',), 'verbose_name': 'Cadastro Pessoa Física', 'verbose_name_plural': 'Cadastro de Pessoas Físicas'},
        ),
    ]
