# Generated by Django 2.1.2 on 2018-10-08 22:49

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('core', '0012_auto_20181008_1943'),
    ]

    operations = [
        migrations.CreateModel(
            name='PF',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('ativo', models.BooleanField(default=True)),
                ('person_type', models.CharField(blank=True, choices=[('PF', 'Pessoa Física'), ('PJ', 'Pessoa Jurídica')], max_length=2, null=True)),
                ('rg', models.CharField(blank=True, max_length=20, null=True)),
                ('cpf', models.CharField(blank=True, max_length=11, null=True)),
                ('birthdate', models.DateField(blank=True, null=True, verbose_name='Data de Nascimento')),
            ],
            options={
                'verbose_name': 'Pessoa Física',
                'verbose_name_plural': 'Pessoas Físicas',
                'ordering': ('first_name',),
            },
            bases=('auth.user', models.Model),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='PJ',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('ativo', models.BooleanField(default=True)),
                ('person_type', models.CharField(blank=True, choices=[('PF', 'Pessoa Física'), ('PJ', 'Pessoa Jurídica')], max_length=2, null=True)),
                ('company_name', models.CharField(max_length=255, verbose_name='Razão Social')),
                ('cnpj', models.CharField(blank=True, max_length=14, null=True)),
            ],
            options={
                'verbose_name': 'Pessoa Jurídica',
                'verbose_name_plural': 'Pessoas Jurídicas',
            },
            bases=('auth.user', models.Model),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='personpf',
            name='user_ptr',
        ),
        migrations.RemoveField(
            model_name='personpj',
            name='user_ptr',
        ),
        migrations.DeleteModel(
            name='PersonPF',
        ),
        migrations.DeleteModel(
            name='PersonPJ',
        ),
    ]
