# Generated by Django 2.1.2 on 2018-10-08 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('core', '0013_auto_20181008_1949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ctp',
            name='criado_por',
        ),
        migrations.RemoveField(
            model_name='ctp',
            name='formato',
        ),
        migrations.RemoveField(
            model_name='ctp',
            name='lineatura',
        ),
        migrations.RemoveField(
            model_name='fineart',
            name='criado_por',
        ),
        migrations.RemoveField(
            model_name='fineart',
            name='formato',
        ),
        migrations.RemoveField(
            model_name='fineart',
            name='papel',
        ),
        migrations.RemoveField(
            model_name='fotolito',
            name='criado_por',
        ),
        migrations.RemoveField(
            model_name='fotolito',
            name='formato',
        ),
        migrations.RemoveField(
            model_name='fotolito',
            name='lineatura',
        ),
        migrations.RemoveField(
            model_name='pf',
            name='user_ptr',
        ),
        migrations.RemoveField(
            model_name='pj',
            name='user_ptr',
        ),
        migrations.RemoveField(
            model_name='provadecor',
            name='criado_por',
        ),
        migrations.RemoveField(
            model_name='provadecor',
            name='formato',
        ),
        migrations.RemoveField(
            model_name='provadecor',
            name='papel',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user_ptr',
        ),
        migrations.DeleteModel(
            name='Ctp',
        ),
        migrations.DeleteModel(
            name='FineArt',
        ),
        migrations.DeleteModel(
            name='Formato',
        ),
        migrations.DeleteModel(
            name='Fotolito',
        ),
        migrations.DeleteModel(
            name='Lineatura',
        ),
        migrations.DeleteModel(
            name='Papel',
        ),
        migrations.DeleteModel(
            name='PF',
        ),
        migrations.DeleteModel(
            name='PJ',
        ),
        migrations.DeleteModel(
            name='ProvaDeCor',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
